{{- if .Values.Ingress.enabled -}}
{{- $releaseName := include "Jenkins-K8s-Deployment.fullname" . -}}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: {{ $releaseName }}-ingress
  lables:
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/managed-by: helm
  {{- include "jenkins-ingress.lables" . | nindent 4}}
  annotations:
  {{- include "jenkins-annotation.annotations" . | nindent 4 }}
spec:
  ingressClassName: alb
  rules:
    - host: jenkins-ingress
      http:
        paths:
        - path: "/"
          pathType: Prefix
          backend:
            service:
              name: {{ include "Jenkins-K8s-Deployment.fullname" . }}-ingress
              port: 
                number: 80
{{- end -}}