{{- $releaseName := include "Jenkins-K8s-Deployment.fullname" . -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $releaseName }}
  namespace: {{ .Values.namespace }}
  annotations:
    app.kubernetes.io/managed-by: helm
    app.kubernetes.io/name: {{ $releaseName }} 
    meta.helm.sh/release-name: {{ $releaseName }}
    meta.helm.sh/release-namespace: {{ .Values.namespace }}
  labels:
    app.kubernetes.io/instance: {{ $releaseName }}
    app.kubernetes.io/name: {{ $releaseName }} 
    app.kubernetes.io/managed-by: helm 
spec:
  replicas: 2
  selector:
    matchLabels:
      app.kubernetes.io/instance: {{ $releaseName }}
  strategy: 
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 2
      maxUnavailable: 1
  template:
    metadata:
      labels:
        app.kubernetes.io/instance: {{ $releaseName }}
    spec:
      serviceAccountName: {{ $releaseName }}-sa
      securityContext: 
        fsGroup: 1000
        runAsUser: 0
      containers:
        - name: {{ $releaseName }}
          image: python
          imagePullPolicy: Always
          livenessProbe:
            httpGet:
              path: "/"
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
            terminationGracePeriodSeconds: 10
          readinessProbe:
            httpGet: 
              path: "/"
              port: {{ .Values.containerPort }}
            initialDelaySeconds: 90
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 5
            successThreshold: 1
          ports:
          - containerPort: {{ .Values.containerPort }}
          initContainers:
            - name: delay
              image: busybox
              command: ["sh", "-c", "sleep 10"]
              volumeMounts:
              - name: jenkins-home
                mountPath: /var/jenkins_home/
          volumes:
          - name: jenkins-home
            persistentVolumeClaim:
              claimName: {{ $releaseName }}-pvc
                    