apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "Jenkins-K8s-Deployment.fullname" . }}-role-binding
  namespace: {{ .Values.namespace }}
roleRef: 
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "Jenkins-K8s-Deployment.fullname" . }}-role
subjects:
- kind: ServiceAccount
  name: {{ include "Jenkins-K8s-Deployment.fullname" . }}-sa
  namespace: {{ .Values.namespace }}